### ISSUE TITLE
kits.yml help?

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [Infernus101/KitUI#10]
can the config be like this

testkit:
  - "260:0:10"
  - "267:0:1:Sword Name:sharpness:3:knockback:1"
  - "302:0:1"
  - "303:0:1:DEFAULT:protection:1"
  - "304:0:1:Leggings Name"
  - "305:0:1"
  - "tell {player} Kit claimed!"
  cooldown:
    hours: 24
    minutes: 30
  effects:
  - "speed:120:10
  money: 50
  info: "This kit is too op XD Cost: 50$"
...

or does it have to be like this

testkit:

  items:
  - "260:0:10"
  - "267:0:1:Sword Name:sharpness:3:knockback:1"
  - "302:0:1"
  - "303:0:1:DEFAULT:protection:1"
  - "304:0:1:Leggings Name"
  - "305:0:1"

  - "tell {player} Kit claimed!"

  cooldown:
    hours: 24
    minutes: 30

  effects:
  - "speed:120:2"

  money: 50

  info: "This kit is too op XD Cost: 50$"
...

**Comment by Infernus101** [comment]
I don't know what you mean... Config has to be like this - 
```
---
testkit:
  # Format: "id:damage:count:name:ench_name:ench_level"

  # If you want only custom name (no enchantments): "id:damage:count:name"

  # If you don't want enchantments or custom name: "id:damage:count"

  # If you want only enchantments (no custom name): "id:damage:count:DEFAULT:ench_name:ench_level" -- you have to put DEFAULT in the name field

  # If you want more than one enchantment just do: "id:damage:count:name:ench1_name:ench1_level:ench2_name:ench2_level"
  # or "id:damage:count:DEFAULT:ench1_name:ench1_level:ench2_name:ench2_level" if you don't want a custom item name

  # Please note: You have to write numeric IDs
  items:
  - "260:0:10"
  - "267:0:1:Sword Name:sharpness:3:knockback:1"
  helmet: "302:0:1"
  chestplate: "303:0:1:DEFAULT:protection:1"
  leggings: "304:0:1:Leggings Name"
  boots: "305:0:1"

  commands: # {player} will get replaced by player's name
  - "tell {player} Kit claimed!"

  cooldown:
    hours: 24
    minutes: 30

  # Format: "name:time:amplifier"
  # Time is in seconds
  effects:
  - "speed:120:2"

  # Add a cost for the kit. Compatible with EconomyAPI only
  # Put 0 if you want the kit to be free
  money: 50

  # Info to show when selected a Kit in UI form
  info: "This kit is too op XD Cost: 50$"
...
```

**Comment by XoticRealmsOwnerandDev** [comment]
no, when like adding a new kit how would i do that

**Comment by Infernus101** [comment]
Just like the test kit in kits.yml but edit and add more stuff like you want

**Comment by XoticRealmsOwnerandDev** [comment]
do i have to have spaces in between the lines

**Comment by Infernus101** [comment]
Do you not know [YAML](https://en.wikipedia.org/wiki/YAML)? Use [YamlLint](http://www.yamllint.com/) to check if your config is right or wrong. To add a new Kit, just copy the test kit and paste it below the last kit, no space or space is fine

**Comment by XoticRealmsOwnerandDev** [comment]
ok thanks

**Comment by XoticRealmsOwnerandDev** [comment]
does this plugin suppot PiggyCustomEnchants

**Comment by Infernus101** [comment]
probably not, try though and make an issue with the error.
