### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by creeperplayer20** [Infernus101/KitUI#107]
Hello @infernus101 I have problem if I set permission for kit to group it didn't works in game kit name is "tools" And I set it to kit.tools in pureperms I'm using dev kitui my API: 3.7.1

**Comment by Infernus101** [comment]
send kits.yml

**Comment by creeperplayer20** [comment]
[kits.yml.zip](https://github.com/Infernus101/KitUI/files/3104588/kits.yml.zip)

**Comment by creeperplayer20** [comment]
![Screenshot_20190423-144856](https://user-images.githubusercontent.com/42560781/56582343-5a5e1500-65d7-11e9-8b63-e5111bf0496d.png)

**Comment by Infernus101** [comment]
Your config isn't set properly.
