### ISSUE TITLE
Permission problem v2

### ISSUE THREAD

**Issue by creeperplayer20** [Infernus101/KitUI#109]
![IMG_20190423_184633](https://user-images.githubusercontent.com/42560781/56600058-2f37ed80-65f8-11e9-8b70-d1c7b444e667.png)

![IMG_20190423_184442](https://user-images.githubusercontent.com/42560781/56600066-34953800-65f8-11e9-92ba-3b5b952f9b74.png)

![Screenshot_20190423-183316](https://user-images.githubusercontent.com/42560781/56600083-39f28280-65f8-11e9-87f3-3d784bfd269c.png)

Again I have problem with permissions

**Comment by Infernus101** [comment]
Your config needs to be set properly...
