### ISSUE TITLE
ce support?

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [Infernus101/KitUI#11]
advanced kits supports this and it looks like kitui and advancedkits are setup kind of the same

https://github.com/poggit-orphanage/AdvancedKits/commit/3242b51106818ff2bebe0ef1fff5e673efb15a89

https://github.com/poggit-orphanage/AdvancedKits/commit/244882dfd5ef19528cd0e1aea581af5ce888e9cb

https://github.com/poggit-orphanage/AdvancedKits/commit/b0b81c0a203f0caeeb4decea40f354e712a5fe78

thoese are the commits to advanced kits where they added the customenchant suppot+bug fixes

can you plz add this it would help alot

**Comment by ghost** [comment]
Yes add it

**Comment by Infernus101** [comment]
Try v1.1

**Comment by ghost** [comment]
@Infernus101of the KitUI or Advanced Kits?

**Comment by Infernus101** [comment]
KitUI
