### ISSUE TITLE
enchants

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [Infernus101/KitUI#18]
do i have to use enchant names or can i use the id for the enchant(vanilla enchants)

**Comment by Infernus101** [comment]
Enchant names provided here--> https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php#L29

**Comment by XoticRealmsOwnerandDev** [comment]
and does the item name in the kits.yml file support color code like §7Iron Sword

**Comment by Infernus101** [comment]
Yes
