### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by ghost** [Infernus101/KitUI#21]
## KitUI Issue
- [ ] Remove/Fix the weird font when asking the info of the Kit, looks a little bezeled when adding colors to the words. 

## Issue description
 Remove/Fix the weird font when asking the info of the Kit, looks a little bezeled when adding colors to the words. 

## Reproducing the issue
1. If any, remove font that could be in use or special characters to make the font of the text look different

## Client information
PocketMine-MP Version: 
PocketMine-MP_1.7dev-356_3614711a_API-3.0.0-ALPHA9.phar
MCPE Version: Minecraft Windows 10/PE 1.2.3
Plugin Version: 1.1.2
PHP version: 7.2

## Optional information
None

```
Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)
```

## Config
...

**Comment by ghost** [comment]
Example, change the KIT MAIN MENU to colored words, it's the same Minecraft Font while the KIT INFO menu shows a different font with color. 

Can you make it where the font is the same Minecraft one like the MAIN MENU font?

**Comment by Infernus101** [comment]
No, that form has a weird font, i didn't change it. Contact Mojang.
