### ISSUE TITLE
Adding pictures to kits in UI?

### ISSUE THREAD

**Issue by YHC2538** [Infernus101/KitUI#23]
## KitUI Issue
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable in English.

Adding pictures to kits?
...

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: (insert commit hash here)
MCPE Version: (insert game version here)
Plugin Version: (insert commit hash here)
PHP version: 7.2

## Optional information
...

```
Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)
```

## Config
...

**Comment by tbhDequan** [comment]
you'll have to make your own plugin like this one to be able to add pictures unless he makes a next one and add support for pictures

**Comment by Infernus101** [comment]
working on it.

**Comment by Infernus101** [comment]
Use v1.1.3

**Comment by YHC2538** [comment]
Thank you, you are awesome and I luv u
