### ISSUE TITLE
How to add custom enchants to items in kit.yml? (PiggyCustomEnchants)

### ISSUE THREAD

**Issue by YHC2538** [Infernus101/KitUI#24]
## KitUI Issue
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable in English.

## Issue description
How to add custom enchants to items in kit? (PiggyCustomEnchants)
Can anyone give me an example of adding custom enchants? Ex. Lifesteal(from piggycustomenchants) how should I do that?

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: (insert commit hash here)
MCPE Version: (insert game version here)
Plugin Version: (insert commit hash here)
PHP version: 7.2

## Optional information
...

```
Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)
```

## Config
...

**Comment by Infernus101** [comment]
Just use this plugin https://github.com/DaPigGuy/PiggyCustomEnchants/ and add the name of the custom enchant you wanna put in kits.yml in enchant section.
