### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pranavbhuv** [Infernus101/KitUI#30]
Hi, 
This plugin reminds me of the modern AdvancedKits, great job on making it! Its now an absolute Essentials, for servers!
Just a feature, can you add permissions to use kits?
Like you need a permission to use a specific Kit. 
Thanks,
Quiv

**Comment by Infernus101** [comment]
kit.(kit name) 
[permission code](https://github.com/Infernus101/KitUI/blob/master/src/Infernus101/KitUI/Kit.php#L157)
[permission info](https://github.com/Infernus101/KitUI#permissions)

**Comment by pranavbhuv** [comment]
by default would everyone have perms

**Comment by Infernus101** [comment]
Nope
