### ISSUE TITLE
FormsAPI

### ISSUE THREAD

**Issue by pranavbhuv** [Infernus101/KitUI#32]
Hi,
This plugin breaks other plugins using FormsAPI.
Latest PMMP
and Latest Plugin

**Comment by Infernus101** [comment]
Forms API branch hasn't been merged with master yet

**Comment by pranavbhuv** [comment]
No, JoJoes formsapi branch

**Comment by Infernus101** [comment]
Sorry, no support for external plugins, try it yourself
