### ISSUE TITLE
Interference

### ISSUE THREAD

**Issue by ghost** [Infernus101/KitUI#35]
## KitUI Issue
- [ ] I have KitUI and ShopUI installed, SOMETIMES when I get the error message on the kit and exit the UI box, I end up seeing the ShopUI instead of KitUI. 
- [ ] When I go to ShopUI and try going to the info UI, it won’t work because of KitUI is blocking it. If I uninstall KitUI then the ShopUI works perfectly but when KitUI and ShopUI both are installed then they end up combining.

## Issue description
KitUI windows are interfering with ShopUI windows

## Reproducing the issue
1. Try getting the error (Unable to afford, No permissions) 
2. Click the Go Back or Exit Button
*This only happens with ShopUI installed SOMETIMES

## Client information
PocketMine-MP Version: #45 PMMP
MCPE Version: 1.2.5
Plugin Version: 1.1.3
PHP version: 7.2

## Optional Information
This error only works with ShopUI installed, I have JoJoes Forms API plugin installed to make ShopUI work.
...

```
Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)
```

## Config
...

**Comment by Infernus101** [comment]
Only pmmp support

**Comment by ghost** [comment]
i am using pmmp

**Comment by Infernus101** [comment]
Yea and this is a plugin's issue

**Comment by pranavbhuv** [comment]
It’s becausw his plugin use packets, and he already set a variable for them. JoJoes uses packets, and has different variables. They conflict each other, thus making this plugin break other UIs...

**Comment by Infernus101** [comment]
Yea this plugin includes API in it, no need for external APIs like jojojojoe's API, whoever made SHOPUI ask them to include API too!!

**Comment by pranavbhuv** [comment]
Your just creating an uncecsery API 
There’s no need of making your own api, JoJoes is the most accepted and many plugins depend on it.
This plugin breaks, it.
Anyways to fix your issue
Here https://github.com/Taylcd/Kit

**Comment by Infernus101** [comment]
Yea because i have no time to check other plugin's API when i can just make my own API and keep it in core -.-, and that plugin is so badly written, good luck, bye bye now!

**Comment by pranavbhuv** [comment]
Kay. But every player is guarnteed to have FormAPI plugins, and all UI plugins use JoJoes, just a suggestion change too it.
