### ISSUE TITLE
Incompatible with other plugins that use Forms

### ISSUE THREAD

**Issue by Awzaw** [Infernus101/KitUI#37]
https://github.com/Infernus101/KitUI/blob/17c8151726b0397bceecff4da7f9e39989ae4b06/src/Infernus101/KitUI/PlayerEvents.php#L71

This changes `$formId` in any ModalFormResponsePacket received.

**Comment by Infernus101** [comment]
Can you create a pull request to fix... @Awzaw

**Comment by Awzaw** [comment]
just use a throwaway variable instead of changing the packet!

**Comment by Awzaw** [comment]
The problem here, and for all other 'UI' plugins is going to be avoiding formId collisions with the core and each other. The current forms-api branch uses a [counter up](https://github.com/pmmp/PocketMine-MP/blob/forms-api/src/pocketmine/Player.php#L309) from 0, so you could choose to use a counter from any large number, for example, or a reverse counter down from the max unsigned 32bit INT I think - but none of those will guarantee there aren't collisions. Alternatively, the best option might be to rewrite it for the forms-api branch, but since that's not yet finished you should probably wait until it's merged with master, and nobody will give you an ETA for that.

**Comment by Infernus101** [comment]
I chose 3200 as [counter](https://github.com/Infernus101/KitUI/blob/master/src/Infernus101/KitUI/UI/Handler.php#L41), whats wrong with that? @Awzaw

**Comment by Awzaw** [comment]
Nothing wrong with that, but you still need to change the code so that line 71 doesn't change the formId in every ModalFormResponsePacket that's checked.

**Comment by Infernus101** [comment]
Does this [branch](https://github.com/Infernus101/KitUI/tree/compatible-with-plugins) fix this issue?

**Comment by Infernus101** [comment]
@Awzaw

**Comment by Awzaw** [comment]
I'd start by fixing the problem with overwriting `formId` (see PR), then worry about collisions.

**Comment by Infernus101** [comment]
Collisions as in different players getting different player's outcomes/outputs? If so, i can fix that easily.. @Awzaw

**Comment by Awzaw** [comment]
I haven't yet looked closely, but will if I have time; I was thinking of formId collisions between plugins, and core too once the forms-api branch is merged, but now you mention it... is that not already handled?

**Comment by Infernus101** [comment]
Done @Awzaw, btw the issue you are talking about can be handled if we could somehow check if the form id is taken/being used or not...

**Comment by Awzaw** [comment]
I've discussed this with PMMP staff, and don't think that's going to happen, although the forms-api branch isn't yet finished so anything is possible...  But for now UI plugins will need to track their own formIds per player, and try to avoid using the same formIds as core and other non forms-api UI plugins.

**Comment by Infernus101** [comment]
Ok so this issue can be closed?

**Comment by Awzaw** [comment]
Testing the latest submission to Poggit now. Ideally you want to avoid doing anything unnecessary in DataPacketReceiveEvent, and I can't see why you need to json_decode formData as early as [this](https://github.com/Infernus101/KitUI/blob/master/src/Infernus101/KitUI/PlayerEvents.php#L68). Also I'd have checked formId **and** the player before you even call `$window->handle($packet)` [here](https://github.com/Infernus101/KitUI/blob/master/src/Infernus101/KitUI/PlayerEvents.php#L77)

**Comment by Infernus101** [comment]
c191c3c?
