### ISSUE TITLE
Permissions didn´t work

### ISSUE THREAD

**Issue by JaapTijmes** [Infernus101/KitUI#41]
The Kit Permission didn´t work

Where is the Problem i can´t find them.
Sorry for my bad English :D
groups.yml of PurePerms 
---
Player:
  alias: gst
  isDefault: true
  inheritance: []
  permissions:
  - kit.command
  - kit.Standart
  worlds:
    City:
      isDefault: true
      permissions: []

## Client information
PocketMine-MP Version: 1.7dev-516
MCPE Version: 1.2.7
Plugin Version: 1.1.7
PHP version: 7.2

**Comment by Infernus101** [comment]
The kit name needs to be in lower case, so the permission should be kit.standart and not kit.Standart
