### ISSUE TITLE
inventory glitch

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Infernus101/KitUI#44]
## KitUI Issue
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable in English.

## Issue description
...
If u have 9 slots in inventory, and try to buy kit, it say ur inventory full and some items didn't send,
but you get no items from kit and your money get took.

## Reproducing the issue
1. ... have 9 slots free
2. ... buy kit

## Client information
PocketMine-MP Version: (insert commit hash here)
MCPE Version: (insert game version here)
Plugin Version: (insert commit hash here)
PHP version: 7.2

## Optional information
...

```
Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)
```

## Config
...

**Comment by TDMidkwhatisxd** [comment]
Can you add a check? Like if u cant send all items , it just wont send any? And it will say clear inventory before selecting a kit?

**Comment by TDMidkwhatisxd** [comment]
proof
https://youtu.be/QvKth8eNe8U

**Comment by TDMidkwhatisxd** [comment]
kit give 6 items, but I had 8 slots left.... it didn't give anything and took my money

**Comment by Infernus101** [comment]
You're using the old version, i removed adding them till inventory gets full feature and added counting the slots before adding the kit, use the latest version

**Comment by TDMidkwhatisxd** [comment]
ok, thx, ill try

**Comment by TDMidkwhatisxd** [comment]
is really old version? I updated 4 days ago it seems + items didn't get added , I could claim the kit without cooldown but money got took.

edit: ill update to see

**Comment by Infernus101** [comment]
Update lang.properties file and config.yml too, and try editing config.yml

**Comment by TDMidkwhatisxd** [comment]
nope , is same, they updated long ago

**Comment by TDMidkwhatisxd** [comment]
---
# Players can't get another kit till they die
one-kit-per-life: false
# Players can claim another kit if they relog(only if one-kit-per-life is true)
reset-on-logout: true
# Start adding items from the first slot of inventory no matter what, will delete the present item at slot
start-from-first: false
# Clears player inventory before adding the kit
clear-inventory: false
# Text on sign for kit form (case-insensitive)
text-on-sign: "-[KitUI]-"
...

**Comment by TDMidkwhatisxd** [comment]
latest version check, same problem

**Comment by TDMidkwhatisxd** [comment]
the glitch is supportable but money is lost ... that's the only problem

**Comment by TDMidkwhatisxd** [comment]
all is latest, config, lang, even plugin, what now? same old glitch

**Comment by Infernus101** [comment]
The inventory glitch is fixed though, right?

**Comment by TDMidkwhatisxd** [comment]
same error, I already had latest plugin ^^ , idk why I updated it

**Comment by Infernus101** [comment]
But there is no message saying "Some of the items weren't added..." in the plugin anymore...

**Comment by TDMidkwhatisxd** [comment]
then i didn't update lang -...-

**Comment by TDMidkwhatisxd** [comment]
because i don't care about lang

**Comment by TDMidkwhatisxd** [comment]
if i update lang my problem will be solved? 0-0

**Comment by TDMidkwhatisxd** [comment]
now i understand why u got confused ... So , kits didn't send because is set to not send, but it take money + i had enough space

**Comment by TDMidkwhatisxd** [comment]
i see you have your own server. Forget about inventory glitch , claim kit with full inventory , and see if u lose money , don't forget to put price on kit

**Comment by TDMidkwhatisxd** [comment]
i hope it gets fixed soon, some ppl in my server cry that they lost money and they have to work for it again -.....-

**Comment by TDMidkwhatisxd** [comment]
i didn't update the lang, but config and plugin were latest

**Comment by TDMidkwhatisxd** [comment]
there is no reason to lie about that ... I really don't have time to troll.

**Comment by Infernus101** [comment]
Check this issue with latest commit

**Comment by TDMidkwhatisxd** [comment]
[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'KitUI v1.1.8': Undefined variable: money on Infernus101\KitUI\PlayerEvents
[18:48:54] [Server thread/CRITICAL]: ErrorException: "Undefined variable: money" (EXCEPTION) in "KitUI_dev-50.phar/src/Infernus101/KitUI/UI/windows/KitInfo" at line 67
[18:48:54] [Server thread/DEBUG]: #0 KitUI_dev-50.phar/src/Infernus101/KitUI/UI/windows/KitInfo(67): pocketmine\error_handler(integer 8, string Undefined variable: money, string phar:///root/12/plugins/KitUI_dev-50.phar/src/Infernus101/KitUI/UI/windows/KitInfo.php, integer 67, array Array())
[18:48:54] [Server thread/DEBUG]: #1 KitUI_dev-50.phar/src/Infernus101/KitUI/UI/windows/KitInfo(96): Infernus101\KitUI\UI\windows\KitInfo->select(string true.)
[18:48:54] [Server thread/DEBUG]: #2 KitUI_dev-50.phar/src/Infernus101/KitUI/PlayerEvents(80): Infernus101\KitUI\UI\windows\KitInfo->handle(pocketmine\network\mcpe\protocol\ModalFormResponsePacket object)

**Comment by TDMidkwhatisxd** [comment]
happens wen I claim a kit and not enough money

**Comment by Infernus101** [comment]
Fixed

**Comment by TDMidkwhatisxd** [comment]
ok , ill try

**Comment by TDMidkwhatisxd** [comment]
fixed
