### ISSUE TITLE
Plugin not working anymore???

### ISSUE THREAD

**Issue by 0pGam3rMC** [Infernus101/KitUI#46]
Hey there infernus! I recently updated your plugin to 1.1.8 and whenever i do /kit it works perfectly, but then when i select a kit nothing happens. Do you know why this is happening?

**Comment by Infernus101** [comment]
Please follow the issue template next time and its probably because of wrong kits.yml, please paste your kits.yml here...

**Comment by XoticRealmsOwnerandDev** [comment]
do you mean 1.2.8? @0pGam3rMC

**Comment by 0pGam3rMC** [comment]
I believe I found out the problem. When I installed ShopUI the plugin no
longer works, when I removed it kits work. Any reason this is happening ?

**Comment by Infernus101** [comment]
Go make an issue over ShopUI

**Comment by 0pGam3rMC** [comment]
Okay

On Jan 3, 2018 1:47 AM, "Infernus" <notifications@github.com> wrote:

Go make an issue over ShopUI

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Infernus101/KitUI/issues/46#issuecomment-354946366>,
or mute
the thread
