### ISSUE TITLE
inv full ?

### ISSUE THREAD

**Issue by vickymaulana** [Infernus101/KitUI#51]
why im use /kit only inventory full ?

**Comment by Infernus101** [comment]
Can you elaborate please?

**Comment by StormCraftMCPE** [comment]
![img-20180127-wa0015](https://user-images.githubusercontent.com/28435438/35472988-1d0ceba0-0371-11e8-81d5-8f642a810cc6.jpg)
![img-20180127-wa0016](https://user-images.githubusercontent.com/28435438/35472991-250fe1ae-0371-11e8-9c6a-f6c9dc2f0ff9.jpg)
![img-20180127-wa0019](https://user-images.githubusercontent.com/28435438/35473001-3a70f038-0371-11e8-89da-be20233b98d2.jpg)
![img-20180127-wa0018](https://user-images.githubusercontent.com/28435438/35473004-40572058-0371-11e8-9977-0a1aa46cd68c.jpg)

**Comment by Infernus101** [comment]
paste your kits.yml and config.yml here @StormCraftMCPE
