### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by OfficialLilKev** [Infernus101/KitUI#54]
28.01 01:07:24 [Server] Server thread/CRITICAL Unhandled exception executing command 'kit eon' in kit: Call to undefined method pocketmine\inventory\PlayerInventory::setHelmet()
28.01 01:07:24 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\inventory\PlayerInventory::setHelmet()" (EXCEPTION) in "/src/KitUI/Kit" at line 68

**Comment by Infernus101** [comment]
Are you using the latest version of KitUI and PMMP too or not?

**Comment by OfficialLilKev** [comment]
Latest pmmp

**Comment by OfficialLilKev** [comment]
Latest of kitui

**Comment by Infernus101** [comment]
then this shouldn't happen because it's calling armor inventory and not player inventory...

**Comment by OfficialLilKev** [comment]
its saying the error correct

**Comment by Infernus101** [comment]
You need to update to v1.1.9 of KitUI @BajanVlogs

**Comment by nasiridrishi** [comment]
@BajanVlogs I tried to reproduce this issue and can't find anything wrong with it!!
