### ISSUE TITLE
Armor issue

### ISSUE THREAD

**Issue by FaanMaario** [Infernus101/KitUI#55]
```

**Comment by Infernus101** [comment]
You aren't using the latest PMMP commit, if you want to use 1.2.7 PMMP, then use KitUI v1.1.8

**Comment by FaanMaario** [comment]
Okay, but I'm already using KitUI 1.1.8

**Comment by Infernus101** [comment]
Check your pmmp commit or try using KitUI 1.1.9

**Comment by FaanMaario** [comment]
Okay thank you.

EDIT: Doesn't work, I didn't give me the kit at all
