### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by BurritoMan46** [Infernus101/KitUI#56]
The Kits Plugin Is Working But I Added Some Kits To My Server And When I Do /kit I Click On The Kit And I Click "Yes" To Get My Kit And I Don't Get Anything. There's Nothing Saying An Error Please Fix It.

~ oqkqq.

**Comment by BurritoMan46** [comment]
Hope You Read This.

**Comment by xXNiceYT** [comment]
PocketMine-MP (PMMP) Split their inventory it’s not $sender->getArmorInventory();

**Comment by BurritoMan46** [comment]
What do u mean?

**Comment by BurritoMan46** [comment]
Ok.

**Comment by xXNiceYT** [comment]
They split
https://github.com/Infernus101/KitUI/blob/master/src/Infernus101/KitUI/Kit.php#L44#L45
https://github.com/Infernus101/KitUI/blob/master/src/Infernus101/KitUI/Kit.php#L72
The function is no longer in Player.php

**Comment by BurritoMan46** [comment]
Okay I Understand.

**Comment by BurritoMan46** [comment]
But Why Tho?

**Comment by BurritoMan46** [comment]
Can It Fix?

**Comment by xXNiceYT** [comment]
I’ll fix it

**Comment by xXNiceYT** [comment]
Nvm you don’t have lastest version, of pmmp stable.
