### ISSUE TITLE
Kit not spawning

### ISSUE THREAD

**Issue by Shelly7w7** [Infernus101/KitUI#62]
When I select a kit nothing happens. The ui just vanishes

**Comment by Infernus101** [comment]
Please follow the issue template and provide more info like plugins etc.

**Comment by Shelly7w7** [comment]
OK so when I uploaded the plugin and typed /kit it spawned a ui with 3 test kits. When I pressed one kit and the ui vanished and didn't gave me anything. If you need a video inform me

**Comment by Infernus101** [comment]
Are you using any other plugins on your server? Please check this issue with no other plugins installed.

**Comment by Shelly7w7** [comment]
can we take this to dms? so I can show you the plugins


On Feb 21, 2018 1:03 PM, "Infernus" <notifications@github.com> wrote:

Are you using any other plugins on your server? Please check this issue
with no other plugins installed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Infernus101/KitUI/issues/62#issuecomment-367243191>,
or mute
the thread

**Comment by Infernus101** [comment]
Yes

**Comment by dev4uhelp** [comment]
don't work as you don't  have economy enabled

**Comment by Shelly7w7** [comment]
Fixed lol
