### ISSUE TITLE
10 apples?

### ISSUE THREAD

**Issue by servantthought** [Infernus101/KitUI#63]
## KitUI Issue
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable in English.

## Issue description
..
I'm only trying out the sample kits and none work I only get 10 apple instead of the enchanted items listed in the kits.yml
Plz help

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: (1.2.10)
Kit-UI Version: (version: "1.2")
MCPE Version: (V1.2.10)
Plugin Version: (insert commit hash here)
PHP version: 7.2

## Optional information
...

```
Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)
```

## Config
...

Note:
I'm also running these other plugins

AllSigns 
Broadcaster 
CombatLogger 
DevTools 
EconomyAPI 
EconomyJob
EconomyLand
EconomyPShop
EconomySell 
EconomyShop 
FactionsPro 
KitUI
LiveXYZ 
MagicWE 
PlanB 
PureChat 
PurePerms 
Slappers
VoteReward 
WorldProtect 
essentialsTP 
iProtector

**Comment by dev4uhelp** [comment]
Open Kit.yml and edit to change what you get... Any problems you can contact me Twitter:Shabzz102

**Comment by servantthought** [comment]
The default code in kit.yml gives you all kinds of stuff but its not working even when i minimize the kit to only one item...

**Comment by shabazshah7** [comment]
This is how mine is setup try it btw for sharpness you need vanilla enchants ... testkit:
  # Format: "id:damage:count:name:ench_name:ench_level"

  # If you want only custom name (no enchantments): "id:damage:count:name"

  # If you don't want enchantments or custom name: "id:damage:count"

  # If you want only enchantments (no custom name): "id:damage:count:DEFAULT:ench_name:ench_level" -- you have to put DEFAULT in the name field

  # If you want more than one enchantment just do: "id:damage:count:name:ench1_name:ench1_level:ench2_name:ench2_level"
  # or "id:damage:count:DEFAULT:ench1_name:ench1_level:ench2_name:ench2_level" if you don't want a custom item name

  # Please note: You have to write numeric IDs
  items:
  - "260:0:10"
  - "267:0:1:Sword Name:sharpness:3:knockback:1"
  helmet: "302:0:1"
  chestplate: "303:0:1:DEFAULT:protection:1"
  leggings: "304:0:1:Leggings Name"
  boots: "305:0:1"

  commands: # {player} will get replaced by player's name
  - "tell {player} Kit claimed!"

  cooldown:
    hours: 0
    minutes: 1

  # Format: "name:time:amplifier"
  # Time is in seconds
  effects:
  - "speed:120:2"

  # Add a cost for the kit. Compatible with EconomyAPI only
  # Put 0 if you want the kit to be free
  money: 50
  
  #Enter image url for the kit. png image. The image will be shown in kit main menu if its compatible.
  image-url: "https://minecraft.gamepedia.com/media/minecraft.gamepedia.com/f/f2/Stone_Sword.png?version=ede6f1623f23eb3959b3d5287dc54bb0"

  # Info to show when selected a Kit in UI form
  info: "This kit is too op XD Cost: 50$"
testkit2:

  items:
  - "260:0:10"
  - "267:0:1:Sword Name:sharpness:3:knockback:1"
  helmet: "302:0:1"
  chestplate: "303:0:1:DEFAULT:protection:1"
  leggings: "304:0:1:Leggings Name"
  boots: "305:0:1"

  commands:
  - "tell {player} Kit 2 claimed!"

  cooldown:
    hours: 0
    minutes: 1

  effects:
  - "speed:120:2"

  money: 250
  
  image-url: ""

  info: "Kit 2! Cost: 250$"
  
Nab:

  items:
  - "260:0:10"
  - "267:0:1:Sword Name:sharpness:3:knockback:1"
  helmet: "302:0:1"
  chestplate: "303:0:1:DEFAULT:protection:1"
  leggings: "304:0:1:Leggings Name"
  boots: "305:0:1"

  commands:
  - "tell {player} Nab claimed!"

  cooldown:
    hours: 0
    minutes: 1

  effects:
  - "speed:120:2"

  money: 150
  
  image-url: ""

  info: "Kit Nab! Cost: 150$"

Supreme:

  items:
  - "466:0:64"
  - "310:0:1:helmet:protection:10"
  - "311:0:1:DEFAULT:protection:10"
  - "312:0:1:Leggings:protection:10"
  - "313:0:1:shoes:protection:10"
  - "276:0:1:Sword:sharpness:10"
  - "276:0:1:Sword:knockback:10"
  commands:
  - "tell {player} Supreme claimed!"

  cooldown:
    hours: 0
    minutes: 1

  effects:
  - "speed:1200:3"

  money: 1500
  
  image-url: ""

  info: "Kit Supreme! Cost: 1500$"
...

**Comment by dev4uhelp** [comment]
Try setup your kits like this Supreme:

  items:
  - "466:0:64"
  - "310:0:1:helmet:protection:10"
  - "311:0:1:DEFAULT:protection:10"
  - "312:0:1:Leggings:protection:10"
  - "313:0:1:shoes:protection:10"
  - "276:0:1:Sword:sharpness:10"
  - "276:0:1:Sword:knockback:10"
  commands:
  - "tell {player} Supreme claimed!"

  cooldown:
    hours: 0
    minutes: 1

  effects:
  - "speed:1200:3"

  money: 1500
  
  image-url: ""

  info: "Kit Supreme! Cost: 1500$"

**Comment by servantthought** [comment]
I figured it out I needed vanilla enchantments plugin for it to work... Sorry for the bother
