### ISSUE TITLE
effect amplifiers dont work

### ISSUE THREAD

**Issue by artulloss** [Infernus101/KitUI#64]
to recreate just try any amplifier other than 1

**Comment by Infernus101** [comment]
Provide more information, including kits.yml

**Comment by artulloss** [comment]
Well I actually I fixed it on my server, little typo in Kit.php, you wrote ambient instead of amplifier.

**Comment by artulloss** [comment]
Not sure if it was purposeful but it fixed the problem for me. Found it by comparing the code that gives effects by poggit-orphange advanced kits to yours.
