### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BogdanMakarchuk** [Infernus101/KitUI#66]
## Issue description
It's strange but why the pictures around the kit do not work

## Reproducing the issue
1. Command: /kit

## Client information
PocketMine-MP Version: 1.7dev-699
Kit-UI Version: 1.2.1
MCPE Version: 1.2.10
Plugin Version: 1.2.1
PHP version: 7.2

...

**Comment by Infernus101** [comment]
It should be mcpe supported images, i dont know what pictures mcpe supports specifically...
