### ISSUE TITLE
ADD PLEASE

### ISSUE THREAD

**Issue by BogdanMakarchuk** [Infernus101/KitUI#67]
I have a wish that is very easy to implement! Could not you add a function for each kit adding the name kit, because on the main page / kit, the name kit does not look great

**Comment by Infernus101** [comment]
i don't understand, what do you mean...?

**Comment by artulloss** [comment]
I think he means to make the plugin the same way you have it on your server, where you can type the kit name after the /kit command and it opens the selection page for that. I too want this as a feature but I get that you want your server to have the best version of it 🙁. On the bright side this would take minimal effort to implement but doubt it would get added.

**Comment by BogdanMakarchuk** [comment]
@artulloss  personally I already added this function on my server, I thought maybe someone else would want to see this function

**Comment by artulloss** [comment]
@BogdanMakarchuk Submit a pull request, however I doubt he'd add it, also could you send me it I really need that functionality.

**Comment by BogdanMakarchuk** [comment]
@artulloss I sent a request to add

**Comment by BogdanMakarchuk** [comment]
@artulloss https://github.com/Infernus101/KitUI/pull/71/commits/e411d1381891b727076ec67ba3ebaf9ed1e43d49
https://github.com/Infernus101/KitUI/pull/70/commits/f16737924da5b88d84c10664ce061764808923d4

**Comment by Infernus101** [comment]
Check if v1.2.2 fixes this!
