### ISSUE TITLE
Color Codes

### ISSUE THREAD

**Issue by pranavbhuv** [Infernus101/KitUI#69]
## KitUI Issue
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable in English.

## Issue description
How do you use COLOR in the Kits? For example how do I make a red font, I tried § but I got a syntax error. I tried &, and it just says &.

## Reproducing the issue
1. Attempt to make a Kit with color.

## Client information
PocketMine-MP Version: 1.7dev-721
Kit-UI Version: Latest
MCPE Version: 1.2.10
Plugin Version: Latest
PHP version: 7.2

## Optional information
...

```
Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)
```

## Config
...

**Comment by Infernus101** [comment]
Kit with color? do you mean kit name on the form with color?

**Comment by DancingXXL** [comment]
Where did you put "§"?

**Comment by Infernus101** [comment]
Check if v1.2.2 fixes this
