### ISSUE TITLE
Make /kit <kitname> work

### ISSUE THREAD

**Issue by artulloss** [Infernus101/KitUI#74]
This plugin would be a lot more useful if instead of advertising your server, you let us have commands that open the info for each individual kit. You currently have this on your server so this would require no effort to code in. I love this plugin, and I'd like to keep using it but without the ability to make slappers that you tap to confirm selection of a kit this plugin is pretty useless. Players get confused that they have to go over and tap a separate slapper to select a kit.

**Comment by Infernus101** [comment]
It's easy, make a pull request, i'll accept.

**Comment by artulloss** [comment]
Alright I'll try to learn some more php basics to get it added 😭

**Comment by artulloss** [comment]
Actually never going to happen, had to switch to Advanced kits because this doesn't have its own permission system and it seems multiworld pureperms doesn't work.
