### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by YHC2538** [Infernus101/KitUI#76]
When I installed the plugin, I did /kit, the first page UI pops up, I clicked on "testkit", nothing happened. theres no 2nd page.  Tried re-installing but its always the same error.

Please help, thanks!

I really dont know whats causing the error...

**Comment by Infernus101** [comment]
Try this plugin without having any other plugin than KitUI and EconomyAPI

**Comment by YHC2538** [comment]
Ah, its ShopUI. Maybe the KitUI and ShopUI has something incompatible? Because KitUI works fine without ShopUI. Are you able to fix that?

**Comment by Infernus101** [comment]
Not until pmmp merges form-api branch

**Comment by YHC2538** [comment]
How long does it take? Estimated time?

**Comment by Infernus101** [comment]
pmmp doesn't give ETAs... so can't really say

**Comment by YHC2538** [comment]
Are there other ways to fix that probem?

**Comment by YHC2538** [comment]
Please help, the shopui plugin Im using is https://github.com/CastleRaid/PlexiumPE-ShopGUI

**Comment by YHC2538** [comment]
Help needed pls

**Comment by YHC2538** [comment]
What do you mean pmmp doesn't give ETAs? I really need this to work
