### ISSUE TITLE
kit.(kit name) perm?

### ISSUE THREAD

**Issue by Antillon7865** [Infernus101/KitUI#82]
Is there any way of getting perms to get a specific kit? Because its not giving any players on my server the perm to get the kit but instead just shows the Menu.

**Comment by smiggy10** [comment]
When doing /kit it says “unknown command do /help for more info”

**Comment by Antillon7865** [comment]
did you add anything to your kits?

**Comment by smiggy10** [comment]
Hmm yep

**Comment by Antillon7865** [comment]
than you added the kits wrong and you need to add kits and items a certain way in order for the plugin to work

**Comment by Antillon7865** [comment]
But so far this plugin is only for my staff because to perm kit.(kitname) doesnt work only the perm kit.command works

**Comment by Antillon7865** [comment]
Nevermind the perm works now I just had an older version of KitUI

**Comment by Antillon7865** [comment]
Nevermind perm still doesn't work it did for (test) kit but not for any other
