### ISSUE TITLE
KITUI BUG ERROR REPORT PLEASE FIX

### ISSUE THREAD

**Issue by haKingdomsCraft** [Infernus101/KitUI#83]
## KitUI Issue
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable in English.

## Issue description
...

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: (insert commit hash here)
Kit-UI Version: (insert commit hash or version from plugin.yml here)
MCPE Version: (insert game version here)
Plugin Version: (insert commit hash here)
PHP version: 7.2

## Optional information
...

```
Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)
```

## Config
...

**Comment by haKingdomsCraft** [comment]
When U DO /kit
And opens Munua
And Click a kit
And Menea remove and I not get kit
Or something please help Discord:haKingdomsCraft#5533

**Comment by haKingdomsCraft** [comment]
Also VER IS 1.2.2
And IN CONSOLE SHOW NO EERORS
BUT IS HAVE ERRORS

**Comment by XoticRealmsOwnerandDev** [comment]
whats your kits.yml   @haKingdomsCraft  you probably have somthing rong in the kits.yml
