### ISSUE TITLE
PLUGIN COOLDOWN TIMER NOT WORK

### ISSUE THREAD

**Issue by haKingdomsCraft** [Infernus101/KitUI#91]
Plugin Cool down Not Work please help
That my Config Kit
---
Starter:
  # Format: "id:damage:count:name:ench_name:ench_level"

  # If you want only custom name (no enchantments): "id:damage:count:name"

  # If you don't want enchantments or custom name: "id:damage:count"

  # If you want only enchantments (no custom name): "id:damage:count:DEFAULT:ench_name:ench_level" -- you have to put DEFAULT in the name field

  # If you want more than one enchantment just do: "id:damage:count:name:ench1_name:ench1_level:ench2_name:ench2_level"
  # or "id:damage:count:DEFAULT:ench1_name:ench1_level:ench2_name:ench2_level" if you don't want a custom item name

  # Please note: You have to write numeric IDs
  items:
  - "260:0:10"
  - "267:0:1:Starter:sharpness:1::deathbringer:1"
  helmet: "302:0:1:Starter:shielded"
  chestplate: "303:0:1:Starter:protection:1:shielded:1"
  leggings: "304:0:1:Starter:shielded:1"
  boots: "305:0:1:Starter:gears:1:shielded:1"

  commands: # {player} will get replaced by player's name
  - "tell {player} Starter Kit claimed!"

  cooldown:
    hours: 24
    minutes: 30

  # Format: "name:time:amplifier"
  # Time is in seconds
  effects:
  - "speed:120:2"
  
  #Kit name to show on the menu, you can use color symbol '§'
  kit-name: "Starter"

  # Add a cost for the kit. Compatible with EconomyAPI only
  # Put 0 if you want the kit to be free
  money: 50
  
  #Enter image url for the kit. png image. The image will be shown in kit main menu if its compatible.
  image-url: "https://minecraft.gamepedia.com/media/minecraft.gamepedia.com/f/f2/Stone_Sword.png?version=ede6f1623f23eb3959b3d5287dc54bb0"

  # Info to show when selected a Kit in UI form
  info: "This kit is too op XD Cost: 50$"
testkit2:

  items:
  - "260:0:10"
  - "267:0:1:Sword Name:sharpness:3:knockback:1"
  helmet: "302:0:1"
  chestplate: "303:0:1:DEFAULT:protection:1"
  leggings: "304:0:1:Leggings Name"
  boots: "305:0:1"

  commands:
  - "tell {player} Kit 2 claimed!"

  cooldown:
    hours: 24
    minutes: 30

  effects:
  - "speed:120:2"
  
  kit-name: "§ctest2"

  money: 250
  
  image-url: ""

  info: "Kit 2! Cost: 250$"
  
testkit3:

  items:
  - "260:0:10"
  - "267:0:1:Sword Name:sharpness:3:knockback:1"
  helmet: "302:0:1"
  chestplate: "303:0:1:DEFAULT:protection:1"
  leggings: "304:0:1:Leggings Name"
  boots: "305:0:1"

  commands:
  - "tell {player} Kit 3 claimed!"

  cooldown:
    hours: 24
    minutes: 30

  effects:
  - "speed:120:2"

  kit-name: "§6test3"

  money: 150
  
  image-url: ""

  info: "Kit 3! Cost: 150$"
...

**Comment by haKingdomsCraft** [comment]
Help me please

**Comment by Haxley** [comment]
See if it works when you're not OP. #89

**Comment by haKingdomsCraft** [comment]
Ohh thx

**Comment by haKingdomsCraft** [comment]
@Haxley Cooldown Not work if i was or unop I test I deop my self and text not work

**Comment by TDMidkwhatisxd** [comment]
there was some errors in console wen i tried it

**Comment by haKingdomsCraft** [comment]
Can u fix it
