### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Infernus101/KitUI#93]
1. Server thread/CRITICAL]: Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'KitUI v1.3.0': Undefined property: Infernus101\KitUI\Kit::$player on Infernus101\KitUI\PlayerEvents
[10:32:37] [Server thread/CRITICAL]: ErrorException: "Undefined property: Infernus101\KitUI\Kit::$player" (EXCEPTION) in "KitUI-master/src/Infernus101/KitUI/Kit" at line 93

2.  [Server thread/CRITICAL]: TypeError: "Return value of pocketmine\nbt\tag\CompoundTag::key() must be of the type string or null, integer returned" (EXCEPTION) in "vendor/pocketmine/nbt/src/tag/CompoundTag" at line 474

**Comment by TDMidkwhatisxd** [comment]
I used default test kits, and used latest github version ....

**Comment by Infernus101** [comment]
Fixed in v1.3.1, stupid mistake lol
